import { Language } from '@/types';

export const LANGUAGES: Language[] = [
  {
    code: 'punjabi',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ'
  },
  {
    code: 'hindi',
    name: 'Hindi',
    nativeName: 'हिंदी'
  },
  {
    code: 'english',
    name: 'English',
    nativeName: 'English'
  }
];

export const TRANSLATIONS = {
  punjabi: {
    appName: 'ਜੀਵਨ+',
    welcome: 'ਸੁਆਗਤ ਹੈ',
    symptomChecker: 'ਲੱਛਣ ਜਾਂਚੋ',
    doctorConsultation: 'ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ',
    pharmacyFinder: 'ਦਵਾਈ ਦੀ ਦੁਕਾਨ',
    healthRecords: 'ਸਿਹਤ ਰਿਕਾਰਡ',
    languageSwitch: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    voiceHelp: 'ਆਵਾਜ਼ ਸਹਾਇਤਾ',
    login: 'ਲੌਗ ਇਨ',
    phoneNumber: 'ਫ਼ੋਨ ਨੰਬਰ',
    sendOTP: 'OTP ਭੇਜੋ',
    enterOTP: 'OTP ਦਾਖਲ ਕਰੋ',
    verify: 'ਤਸਦੀਕ ਕਰੋ',
    fever: 'ਬੁਖਾਰ',
    cough: 'ਖੰਘ',
    bodyPain: 'ਸਰੀਰ ਵਿੱਚ ਦਰਦ',
    headache: 'ਸਿਰ ਦਰਦ',
    yes: 'ਹਾਂ',
    no: 'ਨਹੀਂ',
    notSure: 'ਪਤਾ ਨਹੀਂ',
    videoCall: 'ਵੀਡੀਓ ਕਾਲ',
    audioCall: 'ਆਡੀਓ ਕਾਲ',
    chat: 'ਚੈਟ',
    available: 'ਉਪਲਬਧ',
    notAvailable: 'ਉਪਲਬਧ ਨਹੀਂ',
    back: 'ਵਾਪਸ',
    home: 'ਘਰ',
    emergency: 'ਐਮਰਜੈਂਸੀ',
    callAmbulance: 'ਐਂਬੂਲੈਂਸ ਬੁਲਾਓ',
    nearestHospital: 'ਨਜ਼ਦੀਕੀ ਹਸਪਤਾਲ',
    dailyHealthTips: 'ਰੋਜ਼ਾਨਾ ਸਿਹਤ ਸੁਝਾਅ',
    selectMainSymptom: 'ਆਪਣਾ ਮੁੱਖ ਲੱਛਣ ਚੁਣੋ',
    chooseSymptom: 'ਉਹ ਲੱਛਣ ਚੁਣੋ ਜੋ ਤੁਹਾਨੂੰ ਸਭ ਤੋਂ ਵੱਧ ਪਰੇਸ਼ਾਨ ਕਰਦਾ ਹੈ',
    assessmentComplete: 'ਮੁਲਾਂਕਣ ਪੂਰਾ',
    highPriority: 'ਉੱਚ ਤਰਜੀਹ',
    mediumPriority: 'ਮੱਧਮ ਤਰਜੀਹ',
    lowPriority: 'ਘੱਟ ਤਰਜੀਹ',
    consultDoctorNow: 'ਹੁਣੇ ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰੋ',
    scheduleConsultation: 'ਸਲਾਹ ਲਈ ਸਮਾਂ ਨਿਯਤ ਕਰੋ',
    getFirstAidTips: 'ਪਹਿਲੀ ਸਹਾਇਤਾ ਦੇ ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ',
    checkAnotherSymptom: 'ਕੋਈ ਹੋਰ ਲੱਛਣ ਚੈੱਕ ਕਰੋ',
    question: 'ਸਵਾਲ',
    of: 'ਦਾ',
    priority: 'ਤਰਜੀਹ'
  },
  hindi: {
    appName: 'जीवन+',
    welcome: 'स्वागत है',
    symptomChecker: 'लक्षण जांचें',
    doctorConsultation: 'डॉक्टर से सलाह',
    pharmacyFinder: 'दवाई की दुकान',
    healthRecords: 'स्वास्थ्य रिकॉर्ड',
    languageSwitch: 'भाषा बदलें',
    voiceHelp: 'आवाज सहायता',
    login: 'लॉग इन',
    phoneNumber: 'फोन नंबर',
    sendOTP: 'OTP भेजें',
    enterOTP: 'OTP डालें',
    verify: 'सत्यापित करें',
    fever: 'बुखार',
    cough: 'खांसी',
    bodyPain: 'शरीर में दर्द',
    headache: 'सिर दर्द',
    yes: 'हाँ',
    no: 'नहीं',
    notSure: 'पता नहीं',
    videoCall: 'वीडियो कॉल',
    audioCall: 'ऑडियो कॉल',
    chat: 'चैट',
    available: 'उपलब्ध',
    notAvailable: 'उपलब्ध नहीं',
    back: 'वापस',
    home: 'घर',
    emergency: 'आपातकाल',
    callAmbulance: 'एम्बुलेंस बुलाएं',
    nearestHospital: 'निकटतम अस्पताल',
    dailyHealthTips: 'दैनिक स्वास्थ्य सुझाव',
    selectMainSymptom: 'अपना मुख्य लक्षण चुनें',
    chooseSymptom: 'वह लक्षण चुनें जो आपको सबसे अधिक परेशान करता है',
    assessmentComplete: 'मूल्यांकन पूरा',
    highPriority: 'उच्च प्राथमिकता',
    mediumPriority: 'मध्यम प्राथमिकता',
    lowPriority: 'कम प्राथमिकता',
    consultDoctorNow: 'अभी डॉक्टर से सलाह लें',
    scheduleConsultation: 'परामर्श के लिए समय निर्धारित करें',
    getFirstAidTips: 'प्राथमिक चिकित्सा सुझाव प्राप्त करें',
    checkAnotherSymptom: 'कोई अन्य लक्षण जांचें',
    question: 'प्रश्न',
    of: 'का',
    priority: 'प्राथमिकता'
  },
  english: {
    appName: 'Jeevan+',
    welcome: 'Welcome',
    symptomChecker: 'Check Symptoms',
    doctorConsultation: 'Doctor Consultation',
    pharmacyFinder: 'Find Pharmacy',
    healthRecords: 'Health Records',
    languageSwitch: 'Change Language',
    voiceHelp: 'Voice Help',
    login: 'Login',
    phoneNumber: 'Phone Number',
    sendOTP: 'Send OTP',
    enterOTP: 'Enter OTP',
    verify: 'Verify',
    fever: 'Fever',
    cough: 'Cough',
    bodyPain: 'Body Pain',
    headache: 'Headache',
    yes: 'Yes',
    no: 'No',
    notSure: 'Not Sure',
    videoCall: 'Video Call',
    audioCall: 'Audio Call',
    chat: 'Chat',
    available: 'Available',
    notAvailable: 'Not Available',
    back: 'Back',
    home: 'Home',
    emergency: 'Emergency',
    callAmbulance: 'Call Ambulance',
    nearestHospital: 'Nearest Hospital',
    dailyHealthTips: 'Daily Health Tips',
    selectMainSymptom: 'Select your main symptom',
    chooseSymptom: 'Choose the symptom that bothers you the most',
    assessmentComplete: 'Assessment Complete',
    highPriority: 'HIGH PRIORITY',
    mediumPriority: 'MEDIUM PRIORITY',
    lowPriority: 'LOW PRIORITY',
    consultDoctorNow: 'Consult Doctor Now',
    scheduleConsultation: 'Schedule Consultation',
    getFirstAidTips: 'Get First Aid Tips',
    checkAnotherSymptom: 'Check Another Symptom',
    question: 'Question',
    of: 'of',
    priority: 'PRIORITY'
  }
};